module.exports = {
  content: ['./src/**/*.{html,js}'],
  theme: {
    extend: {
      colors: {
        'custom-light': '#F5F5F5',
        'custom-dark': '#111A2C',
        'custom-yellow': '#DBDBA9',
        'custom-darkgreen': '#04BF9D',
        'custom-lightgreen': '#5BD963',
        'custom-pink': '#BF7ABB',
        'custom-purple': '#9F6AFF',
        'custom-gray': '#D9D9D9',
        'custom-darkblue': '#59A8D9',
        'custom-lightblue': '#85D3F2',
        'custom-orange': '#C8846C',

      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
        jetBrains: ['JetBrains Mono', 'monospace'],
        merriweather: ['Merriweather', 'serif'],
      },
      fontSize: {
        'h1-lg': '4rem',
        'h1-md': '3.5rem',
        'h1-sm': '2.5rem',
        'h2-lg': '4rem',
        'h2-md': '2.5rem',
        'h2-sm': '2rem',
        'h3-lg': '3rem',
        'h3-md': '2.5rem',
        'h3-sm': '2rem',
        'body-lg': '1.5rem',
        'body-md': '1rem',
        'body-sm': '0.8rem',
      },
      fontWeight: {
        thin: '100',
        extralight: '200',
        light: '300',
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
    },
  },
  plugins: [],
};
